server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Cadmus-Realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: cadmus-miniautorizador
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/miniautorizador
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador?serverTimezone=America/Sao_Paulo
    username: root
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
    hibernate:
      ddl-auto: create
    show-sql: true
  profiles:
    active: dev

jwt:
  auth:
    converter:
      resource-id: cadmus-client
      principle-attribute: preferred_username

springdoc:
  swagger-ui:
    path: twd.html
